name: Cypress Frontend Web E2E test
on: [push]

jobs:
  cypress-e2e-web-tests:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout branch HEAD SHA
        uses: actions/checkout@v3.3.0

      - run: echo $GITHUB_WORKSPACE

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5

